import os
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

import unittest
from unittest.mock import patch, MagicMock
from app.intelligence.parser import parse_pdf
from app.intelligence.repo_indexer import index_repository
from app.intelligence.llm import extract_claims, map_claims_to_repo, _LLM_CACHE
from app.schemas.artifacts import ClaimExtractionArtifact, ClaimMappingsArtifact

class TestWS4(unittest.TestCase):
    
    def test_paper_parsing(self):
        # Using real PDF generated by fpdf2
        fixture_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "fixtures", "test_paper.pdf"))
        
        result = parse_pdf(fixture_path)
        
        self.assertIn("content_hash", result)
        self.assertIn("paper_date", result)
        self.assertTrue(len(result["sections"]) > 0)
        # Check that Abstract is somewhere in the first section's text or title
        first_section_text = result["sections"][0]["title"] + "\\n" + result["sections"][0]["text"]
        self.assertIn("Abstract", first_section_text)
        
        # Verify tables extraction
        has_metric = False
        if result.get("tables"):
            for row in result["tables"][0]["content"]:
                if "Metric" in row or any("Metric" in col for col in row):
                    has_metric = True
        self.assertTrue(has_metric, "Table extraction failed or missed 'Metric' column")
        
    @patch("app.intelligence.parser.fitz.open")
    @patch("app.intelligence.parser.pdfplumber.open")
    def test_paper_parsing_date_extraction(self, mock_pdfplumber, mock_fitz_open):
        mock_doc = MagicMock()
        mock_page = MagicMock()
        mock_page.get_text.return_value = "arXiv:2103.00020v1 [cs.LG] 27 Feb 2021\nAbstract..."
        mock_doc.__len__.return_value = 1
        mock_doc.__getitem__.return_value = mock_page
        mock_fitz_open.return_value = mock_doc
        
        mock_pdf = MagicMock()
        mock_pdf.pages = []
        mock_pdfplumber.return_value.__enter__.return_value = mock_pdf
        
        # We need a dummy file for the hash, so create one
        with open("dummy_test.pdf", "w") as f:
            f.write("dummy")
            
        result = parse_pdf("dummy_test.pdf")
        os.remove("dummy_test.pdf")
        
        self.assertEqual(result["paper_date"], "2021-02-27T00:00:00Z")
        
    def test_repo_indexer(self):
        # Create a dummy repo structure
        os.makedirs("test_repo", exist_ok=True)
        with open("test_repo/main.py", "w") as f:
            f.write("import argparse\nimport hydra\nparser = argparse.ArgumentParser()\nparser.add_argument('--epochs')\n")
        with open("test_repo/requirements.txt", "w") as f:
            f.write("torch\n")
        with open("test_repo/README.md", "w") as f:
            f.write("Run this:\npython main.py --epochs 10\n")
            
        with open("test_repo/config.yaml", "w") as f:
            f.write("epochs: 10\nhydra:\n  run:\n    dir: .\n")
            
        # Create a git repository to test git date extraction
        import subprocess
        subprocess.check_call(["git", "init"], cwd="test_repo")
        subprocess.check_call(["git", "config", "user.email", "test@test.com"], cwd="test_repo")
        subprocess.check_call(["git", "config", "user.name", "Test"], cwd="test_repo")
        subprocess.check_call(["git", "add", "."], cwd="test_repo")
        subprocess.check_call(["git", "commit", "-m", "init"], cwd="test_repo")
        
        # Get actual commit date to assert
        commit_date = subprocess.check_output(["git", "log", "-1", "--format=%cI"], cwd="test_repo", text=True).strip()
            
        result = index_repository("test_repo")
        
        self.assertIn("repo_hash", result)
        self.assertIn("repository_date", result)
        self.assertIsNotNone(result["repository_date"])
        self.assertIn("main.py", result["entry_scripts"])
        self.assertIn("main.py", result["argparse_interfaces"])
        self.assertIn("--epochs", result["argparse_interfaces"]["main.py"])
        self.assertIn("requirements.txt", result["dependencies"])
        self.assertIn("python main.py --epochs 10", result["readme_commands"])
        self.assertIn("config.yaml", result["config_files"])
        self.assertTrue(result["uses_hydra"])
        self.assertEqual(result["repository_date"], commit_date)
        
        import shutil
        shutil.rmtree("test_repo", ignore_errors=True)
        
    @patch('app.intelligence.llm.get_llm_client')
    def test_claim_extraction(self, mock_get_client):
        mock_client = MagicMock()
        mock_client.chat.completions.create.return_value = ClaimExtractionArtifact(
            assessment_id="test_assessment",
            claims=[{
                "claim_id": "c1",
                "experiment": "Exp 1",
                "dataset": "CIFAR",
                "metric": "Accuracy",
                "value": 0.95,
                "page": 1,
                "evidence": {"value": {"quote": "accuracy is 0.95", "page": 1}}
            }],
            settings={
                "epochs": 10,
                "evidence": {"epochs": {"quote": "we trained for 10 epochs", "page": 2}}
            }
        )
        mock_get_client.return_value = mock_client
        
        # Call extraction
        sections = [{"title": "Test Title", "text": "some text", "page": 1}]
        result = extract_claims(sections, "hash123")
        
        self.assertEqual(len(result.claims), 1)
        self.assertEqual(result.claims[0].value, 0.95)
        self.assertEqual(result.claims[0].evidence["value"].quote, "accuracy is 0.95")
        
        # Test caching
        self.assertIn("claims_hash123", _LLM_CACHE)
        
        # Change mock to see if cache is hit
        mock_client.chat.completions.create.side_effect = Exception("Should not be called")
        cached_result = extract_claims(sections, "hash123")
        self.assertEqual(cached_result.claims[0].value, 0.95)
        
    @patch('app.intelligence.llm.get_llm_client')
    @patch('app.intelligence.llm.time.sleep')
    def test_claim_extraction_chunking(self, mock_sleep, mock_get_client):
        # Create a large paper with multiple sections that exceed the 8000 char limit
        # This will test chunking, merging, and deduplication
        sections = []
        for i in range(10):
            # Each section is 1000 chars of 'A'
            sections.append({
                "title": f"Section {i}",
                "text": "A" * 1000,
                "page": i
            })
        
        # This is 10,000 chars total, so it should be split into 2 chunks
        
        mock_client = MagicMock()
        # Side effect to return different results for each chunk
        def side_effect(*args, **kwargs):
            if mock_client.chat.completions.create.call_count == 1:
                return ClaimExtractionArtifact(
                    assessment_id="test",
                    claims=[{
                        "claim_id": "c1", "experiment": "Exp 1", "dataset": "Data 1", "split": "test", "metric": "Acc", "value": 0.9, "page": 1,
                        "evidence": {"value": {"quote": "acc 0.9", "page": 1}}
                    }],
                    settings={"epochs": 10, "evidence": {"epochs": {"quote": "10 epochs", "page": 1}}}
                )
            else:
                return ClaimExtractionArtifact(
                    assessment_id="test",
                    claims=[
                        # Duplicate claim (should be merged/deduplicated)
                        {
                            "claim_id": "c2", "experiment": "Exp 1", "dataset": "Data 1", "split": "test", "metric": "Acc", "value": 0.9, "page": 1,
                            "evidence": {"value": {"quote": "acc 0.9", "page": 1}}
                        },
                        # New claim
                        {
                            "claim_id": "c3", "experiment": "Exp 2", "dataset": "Data 2", "split": "val", "metric": "F1", "value": 0.8, "page": 2,
                            "evidence": {"value": {"quote": "f1 0.8", "page": 2}}
                        }
                    ],
                    settings={"hardware": "V100", "evidence": {"hardware": {"quote": "used V100", "page": 2}}}
                )
        
        mock_client.chat.completions.create.side_effect = side_effect
        mock_get_client.return_value = mock_client
        
        result = extract_claims(sections, "chunkhash123")
        
        # Verify 2 chunks were processed
        self.assertEqual(mock_client.chat.completions.create.call_count, 2)
        # Verify sleep was called for pacing between chunks
        mock_sleep.assert_called_once_with(25)
        
        # Verify claims are merged and deduplicated (Exp 1 appears twice, so 2 unique claims total)
        self.assertEqual(len(result.claims), 2)
        
        # Verify settings are merged
        self.assertEqual(result.settings.epochs, 10)
        self.assertEqual(result.settings.hardware, "V100")
        
        # Verify missing fields remain None
        self.assertIsNone(result.settings.seeds)
        
        # Verify paper-hash caching works (subsequent call uses cache)
        mock_client.chat.completions.create.call_count = 0
        cached_result = extract_claims(sections, "chunkhash123")
        self.assertEqual(mock_client.chat.completions.create.call_count, 0)
        self.assertEqual(len(cached_result.claims), 2)
        
    @patch('app.intelligence.llm.get_llm_client')
    @patch('app.intelligence.llm.time.sleep')
    def test_claim_extraction_rate_limit_failure_and_resume(self, mock_sleep, mock_get_client):
        from app.intelligence.llm import extract_claims, RateLimitTooLongException
        from app.schemas.artifacts import ClaimExtractionArtifact, ClaimData, ExperimentSettings
        import openai
        
        sections = [
            {"title": "Section 1", "text": "A" * 9000, "page": 1},
            {"title": "Section 2", "text": "B" * 9000, "page": 2}
        ]
        
        mock_client = MagicMock()
        
        # First chunk succeeds, second chunk hits a long rate limit
        mock_client.chat.completions.create.side_effect = [
            ClaimExtractionArtifact(
                assessment_id="test",
                claims=[
                    ClaimData(claim_id="c1", experiment="e1", metric="m1", value=1.0, page=1, evidence={"e": {"quote": "q", "page": 1}})
                ],
                settings=ExperimentSettings(evidence={})
            ),
            Exception("Rate limit reached. Please try again in 5m20s.")
        ]
        mock_get_client.return_value = mock_client
        
        hash_val = "ratelimit_hash_123"
        
        # Test that extraction explicitly fails when the second chunk fails
        with self.assertRaises(RateLimitTooLongException) as context:
            extract_claims(sections, hash_val)
            
        self.assertTrue("Required wait is" in str(context.exception))
        
        # Verify first chunk was cached but final artifact was not created
        from app.intelligence.llm import _LLM_CACHE
        self.assertIn(f"claims_{hash_val}_chunk_0", _LLM_CACHE)
        self.assertNotIn(f"claims_{hash_val}", _LLM_CACHE)
        
        # Second run: Should resume and NOT call the LLM for chunk 0
        mock_client.chat.completions.create.side_effect = [
            ClaimExtractionArtifact(
                assessment_id="test",
                claims=[
                    ClaimData(claim_id="c2", experiment="e2", metric="m2", value=2.0, page=2, evidence={"e": {"quote": "q2", "page": 2}})
                ],
                settings=ExperimentSettings(evidence={})
            )
        ]
        
        # Reset mock call count
        mock_client.chat.completions.create.reset_mock()
        
        result = extract_claims(sections, hash_val)
        
        # The LLM should only have been called ONCE for chunk 1, since chunk 0 was cached
        self.assertEqual(mock_client.chat.completions.create.call_count, 1)
        
        # Both claims should be present in the final result
        self.assertEqual(len(result.claims), 2)
        self.assertEqual(result.claims[0].claim_id, "c1")
        self.assertEqual(result.claims[1].claim_id, "c2")

    @patch('app.intelligence.llm.get_llm_client')
    @patch('app.intelligence.llm.time.sleep')
    def test_claim_extraction_failure(self, mock_sleep, mock_get_client):
        # Create a paper with sections
        sections = [{"title": "Section 1", "text": "A" * 1000, "page": 1}]
        
        mock_client = MagicMock()
        # Simulate unrecoverable extraction failure
        mock_client.chat.completions.create.side_effect = Exception("Tool call validation failed")
        mock_get_client.return_value = mock_client
        
        # Test that extraction explicitly fails when a chunk fails
        with self.assertRaises(Exception) as context:
            extract_claims(sections, "failhash123")
            
        self.assertTrue("Tool call validation failed" in str(context.exception))
        
    @patch('app.intelligence.llm.get_llm_client')
    def test_claim_mapping(self, mock_get_client):
        mock_client = MagicMock()
        mock_client.chat.completions.create.return_value = ClaimMappingsArtifact(
            assessment_id="test_assessment",
            mappings=[{
                "claim_id": "c1",
                "script": "main.py",
                "command": "python main.py --epochs 10",
                "confidence": 0.9,
                "evidence": "Matches the README command"
            }]
        )
        mock_get_client.return_value = mock_client
        
        result = map_claims_to_repo([{"claim_id": "c1"}], {"entry_scripts": ["main.py"]})
        self.assertEqual(len(result.mappings), 1)
        self.assertEqual(result.mappings[0].script, "main.py")
        self.assertEqual(result.mappings[0].confidence, 0.9)

    @patch("app.intelligence.parser.urllib.request.urlopen")
    def test_arxiv_resolution(self, mock_urlopen):
        # Setup mock network response
        import io
        from app.intelligence.parser import resolve_paper_source
        from app.core.config import settings
        import urllib.error
        
        mock_response = MagicMock()
        mock_response.read.return_value = b"%PDF-1.4 Mock arXiv PDF Content"
        mock_response.__enter__.return_value = mock_response
        mock_urlopen.return_value = mock_response

        cache_dir = os.path.join(settings.STORAGE_DIR, "_arxiv_test_cache")
        
        # 1. Test successful resolution of 'arxiv:1803.03635'
        path1 = resolve_paper_source("arxiv:1803.03635", cache_dir)
        self.assertTrue(path1.endswith("1803.03635.pdf"))
        self.assertTrue(os.path.exists(path1))
        
        # Clean up
        os.remove(path1)

        # 2. Test successful resolution of '1803.03635'
        path2 = resolve_paper_source("1803.03635", cache_dir)
        self.assertTrue(path2.endswith("1803.03635.pdf"))
        self.assertTrue(os.path.exists(path2))
        
        # Clean up
        os.remove(path2)
        
        # 3. Test successful resolution of 'https://arxiv.org/abs/1803.03635'
        path3 = resolve_paper_source("https://arxiv.org/abs/1803.03635", cache_dir)
        self.assertTrue(path3.endswith("1803.03635.pdf"))
        self.assertTrue(os.path.exists(path3))
        
        # Clean up
        os.remove(path3)
        
        # 4. Test failure on invalid arXiv ID simulating HTTP 404
        mock_urlopen.side_effect = urllib.error.URLError("HTTP Error 404: Not Found")
        with self.assertRaises(ValueError):
            resolve_paper_source("arxiv:9999.99999", cache_dir)
            
    @patch("app.intelligence.parser.ssl.create_default_context")
    @patch("app.intelligence.parser.urllib.request.urlopen")
    def test_arxiv_ssl_verification(self, mock_urlopen, mock_ssl_context):
        import certifi
        import io
        import urllib.error
        from app.intelligence.parser import resolve_paper_source
        from app.core.config import settings

        mock_response = MagicMock()
        mock_response.read.return_value = b"%PDF-1.4 Mock arXiv PDF Content"
        mock_response.__enter__.return_value = mock_response
        mock_urlopen.return_value = mock_response
        
        mock_ctx = MagicMock()
        mock_ssl_context.return_value = mock_ctx

        cache_dir = os.path.join(settings.STORAGE_DIR, "_arxiv_test_cache_ssl")
        
        # Test successful resolution triggers correct SSL configuration
        path1 = resolve_paper_source("arxiv:1803.03635", cache_dir)
        
        mock_ssl_context.assert_called_once_with(cafile=certifi.where())
        
        # Verify the context is actually passed to urlopen
        called_args, called_kwargs = mock_urlopen.call_args
        self.assertIn('context', called_kwargs)
        self.assertEqual(called_kwargs['context'], mock_ctx)
        
        # Clean up
        if os.path.exists(path1):
            os.remove(path1)

    @patch("app.intelligence.parser.urllib.request.urlopen")
    @patch("app.pipeline.stages_ws4.parse_pdf")
    def test_paper_parsing_stage_with_arxiv(self, mock_parse_pdf, mock_urlopen):
        # 5. Test PaperParsingStage directly receives the downloaded PDF path
        mock_parse_pdf.return_value = {
            "content_hash": "mockhasharxiv",
            "paper_date": "2018-03-01T00:00:00Z",
            "sections": [],
            "tables": []
        }
        mock_response = MagicMock()
        mock_response.read.return_value = b"%PDF-1.4 Mock arXiv PDF Content"
        mock_response.__enter__.return_value = mock_response
        mock_urlopen.return_value = mock_response

        # Setup Assessment with arXiv source
        import uuid
        from app.db.models import Assessment
        from app.pipeline.stages_ws4 import PaperParsingStage
        
        assessment_id = str(uuid.uuid4())
        assessment = Assessment(
            id=assessment_id,
            paper_source="1803.03635",
            paper_input_type="url",
            repository_source="https://github.com/test/repo",
            repository_input_type="url"
        )
        
        mock_db = MagicMock()
        mock_query = MagicMock()
        mock_filter = MagicMock()
        mock_db.query.return_value = mock_query
        mock_query.filter.return_value = mock_filter
        mock_filter.first.return_value = assessment

        # Execute Stage
        stage = PaperParsingStage()
        # Mock create_db_session to use test DB
        stage._create_db_session = MagicMock(return_value=mock_db)
        
        # Mock save_artifact to avoid DB schema errors
        mock_out = MagicMock()
        mock_out.type = "PaperDocumentArtifact"
        stage.save_artifact = MagicMock(return_value=mock_out)
        
        output_artifacts = stage.execute(assessment_id, [])

        self.assertEqual(len(output_artifacts), 1)
        self.assertEqual(output_artifacts[0].type, "PaperDocumentArtifact")
        
        # Verify parse_pdf was called with the cached arxiv file path, not '1803.03635' directly
        called_path = mock_parse_pdf.call_args[0][0]
        self.assertTrue(called_path.endswith("1803.03635.pdf"))
        self.assertNotEqual(called_path, "1803.03635")


if __name__ == '__main__':
    unittest.main()
